name: Build site
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: nikeee/setup-pandoc@v1
      - run: make
      - run: chmod -R +rw out
      - uses: actions/upload-pages-artifact@v3
        with: 
          path: out/


  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    needs: build
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ github.token }}
          artifact_name: github-pages

## deploy:
##   # Add a dependency to the build job
##   needs: build
##
##   # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
##   permissions:
##     pages: write      # to deploy to Pages
##     id-token: write   # to verify the deployment originates from an appropriate source
##
##   # Deploy to the github-pages environment
##   environment:
##     name: github-pages
##     url: ${{ steps.deployment.outputs.page_url }}
##
##   # Specify runner + deployment step
##   runs-on: ubuntu-latest
##   steps:
##     - name: Deploy to GitHub Pages
##       id: deployment
##       uses: actions/deploy-pages@v3
