name: Build site
on: push
jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: nikeee/setup-pandoc@v1
      - run: make
      - uses: actions/upload-pages-artifact@master
        with: 
          path: out/
